"use strict";

const INVOCADOR_DE_SOMBRAS = {
  m1: {
    name: "Shadow Strike",
    damage: 20,
    range: 85,
    cooldown: 0.3,
    startup: 0.07,
    active: 0.1,
    recovery: 0.11,
  },
  passive: {
    radius: 120,
    projectileSlow: 0.4,
    dashSlow: 0.1,
  },
  rika: {
    energy: 35,
    cooldown: 10,
    range: 150,
    coneAngle: 1.0,
    damage: 75,
    knockback: 400,
    startup: 0.12,
    radius: 32,
    guardBreak: false,
  },
  dashSlash: {
    energy: 20,
    cooldown: 4,
    distance: 100,
    damage: 30,
    startup: 0.04,
    active: 0.1,
    recovery: 0.08,
    through: true,
  },
  fullRika: {
    energy: 50,
    cooldown: 30,
    duration: 18,
    swipeDamage: 35,
    slamDamage: 55,
    grabDamage: 80,
    attackInterval: 1.8,
    range: 190,
    startup: 0.25,
    swipeKnockback: 180,
    slamKnockback: 320,
    grabThrow: 450,
  },
  pureLove: {
    energy: 85,
    cooldown: 42,
    damage: 380,
    radius: 240,
    startup: 0.55,
    knockback: 550,
    guardBreak: true,
  },
  domain: {
    energyInitial: 75,
    startup: 0.8,
    drainPerSecond: 5,
    freezeDps: 10,
    katanaDamage: 20,
    katanaInterval: 0.5,
    radius: 380,
    speedBuff: 1.15,
    cooldownBuff: 0.7,
    cooldown: 70,
    conflictExtraDrain: 5,
    collapseStun: 0.7,
    sureHitRange: 180,
  },
};

module.exports = {
  INVOCADOR_DE_SOMBRAS,
};
