"use strict";

const YUTA = {
  m1: {
    name: "Katana Combat",
    damage: 20,
    range: 90,
    cooldown: 0.28,
    startup: 0.07,
    active: 0.1,
    recovery: 0.1,
  },
  rika: {
    energy: 40,
    cooldown: 12,
    range: 140,
    coneAngle: 1.2,
    damage: 85,
    knockback: 450,
    startup: 0.15,
    radius: 34,
    guardBreak: true,
  },
  dashSlash: {
    energy: 20,
    cooldown: 4,
    distance: 110,
    damage: 35,
    startup: 0.05,
    active: 0.12,
    recovery: 0.08,
    through: true,
  },
  fullRika: {
    energy: 55,
    cooldown: 35,
    duration: 20,
    swipeDamage: 40,
    slamDamage: 65,
    grabDamage: 90,
    attackInterval: 1.8,
    range: 200,
    startup: 0.3,
    swipeKnockback: 200,
    slamKnockback: 350,
    grabThrow: 500,
  },
  pureLove: {
    energy: 90,
    cooldown: 45,
    damage: 420,
    radius: 260,
    startup: 0.6,
    knockback: 600,
    guardBreak: true,
  },
  domain: {
    energyInitial: 80,
    startup: 1.0,
    drainPerSecond: 6,
    katanaDamage: 25,
    katanaInterval: 0.5,
    radius: 400,
    speedBuff: 1.25,
    cooldownBuff: 0.6,
    cooldown: 75,
    conflictExtraDrain: 5,
    collapseStun: 0.75,
    sureHitRange: 200,
  },
};

module.exports = {
  YUTA,
};
