"use strict";

const ENEMY_TEMPLATES = {
  shade: {
    tier: "weak",
    role: "pressure",
    hp: 120,
    speed: 110,
    radius: 18,
    attackDamage: 22,
    attackRange: 46,
    attackStartup: 0.35,
    attackCooldown: 1.5,
    xp: 34,
  },
  stalker: {
    tier: "weak",
    role: "aggressive",
    hp: 95,
    speed: 145,
    radius: 16,
    attackDamage: 18,
    attackRange: 36,
    attackStartup: 0.25,
    attackCooldown: 1.2,
    xp: 38,
  },
  caster: {
    tier: "strong",
    role: "zone_control",
    hp: 110,
    speed: 84,
    radius: 18,
    attackDamage: 28,
    attackRange: 400,
    attackStartup: 0.45,
    attackCooldown: 2.1,
    xp: 45,
  },
  elite: {
    tier: "strong",
    role: "punisher",
    hp: 290,
    speed: 126,
    radius: 24,
    attackDamage: 42,
    attackRange: 62,
    attackStartup: 0.35,
    attackCooldown: 1.3,
    xp: 105,
  },
  boss: {
    tier: "boss",
    role: "cinematic_boss",
    hp: 4200,
    speed: 95,
    radius: 34,
    attackDamage: 64,
    attackRange: 90,
    attackStartup: 0.6,
    attackCooldown: 1.8,
    xp: 500,
  },
  rotten_husk: {
    tier: "weak",
    role: "pressure",
    hp: 120,
    speed: 145,
    radius: 18,
    attackDamage: 14,
    attackRange: 65,
    attackStartup: 0.35,
    attackCooldown: 1.2,
    xp: 26,
  },
  cursed_runner: {
    tier: "weak",
    role: "aggressive",
    hp: 90,
    speed: 250,
    radius: 16,
    attackDamage: 12,
    attackRange: 52,
    attackStartup: 0.28,
    attackCooldown: 1.0,
    xp: 28,
  },
  bone_spearer: {
    tier: "strong",
    role: "zone_control",
    hp: 380,
    speed: 155,
    radius: 22,
    attackDamage: 18,
    attackRange: 62,
    attackStartup: 0.36,
    attackCooldown: 1.35,
    xp: 90,
  },
  void_priest: {
    tier: "strong",
    role: "spacing_control",
    hp: 420,
    speed: 170,
    radius: 22,
    attackDamage: 20,
    attackRange: 68,
    attackStartup: 0.4,
    attackCooldown: 1.45,
    xp: 98,
  },
  abyss_howler: {
    tier: "strong",
    role: "rushdown",
    hp: 460,
    speed: 220,
    radius: 24,
    attackDamage: 24,
    attackRange: 72,
    attackStartup: 0.34,
    attackCooldown: 1.2,
    xp: 110,
  },
  chaos_executioner: {
    tier: "strong",
    role: "punisher",
    hp: 620,
    speed: 150,
    radius: 28,
    attackDamage: 32,
    attackRange: 82,
    attackStartup: 0.44,
    attackCooldown: 1.55,
    xp: 140,
  },
  mirror_stalker: {
    tier: "super",
    role: "mindgame",
    hp: 850,
    speed: 230,
    radius: 26,
    attackDamage: 38,
    attackRange: 88,
    attackStartup: 0.36,
    attackCooldown: 1.45,
    xp: 180,
  },
  calamity_beast: {
    tier: "super",
    role: "arena_control",
    hp: 1100,
    speed: 195,
    radius: 30,
    attackDamage: 42,
    attackRange: 92,
    attackStartup: 0.45,
    attackCooldown: 1.6,
    xp: 220,
  },
  void_samurai: {
    tier: "super",
    role: "duelist",
    hp: 980,
    speed: 205,
    radius: 24,
    attackDamage: 40,
    attackRange: 86,
    attackStartup: 0.3,
    attackCooldown: 1.25,
    xp: 210,
  },
  seraph_of_ruin: {
    tier: "super",
    role: "air_control",
    hp: 1300,
    speed: 190,
    radius: 31,
    attackDamage: 44,
    attackRange: 96,
    attackStartup: 0.46,
    attackCooldown: 1.65,
    xp: 240,
  },
  fallen_vessel: {
    tier: "boss",
    role: "cinematic_boss",
    hp: 6000,
    speed: 190,
    radius: 36,
    attackDamage: 58,
    attackRange: 104,
    attackStartup: 0.42,
    attackCooldown: 1.55,
    xp: 1200,
  },
};

function createEnemy(id, type, x, y, scale = 1) {
  const base = ENEMY_TEMPLATES[type] || ENEMY_TEMPLATES.rotten_husk;
  const hpScale = 0.9 + scale * 0.1;
  const speedScale = 0.94 + scale * 0.06;
  const damageScale = 0.9 + scale * 0.1;
  const strongHpBonus = base.tier === "strong" ? 1.2 : 1;
  const baseHp = base.hp * strongHpBonus;

  return {
    id,
    kind: "enemy",
    type,
    tier: base.tier,
    role: base.role,
    x,
    y,
    vx: 0,
    vy: 0,
    faceX: 1,
    faceY: 0,
    hp: Math.round(baseHp * hpScale),
    maxHp: Math.round(baseHp * hpScale),
    speed: base.speed * speedScale,
    radius: base.radius,
    damage: Math.round(base.attackDamage * damageScale),
    attackRange: base.attackRange,
    attackCooldownBase: base.attackCooldown,
    attackCooldown: 0,
    attackWindup: base.attackStartup,
    windupTimer: 0,
    recoveryTimer: 0,
    cast: null,
    castTier: null,
    abilityCooldowns: {},
    aiOrbitDir: Math.random() < 0.5 ? -1 : 1,
    targetId: null,
    alive: true,
    hitFlash: 0,
    state: "idle",
    xpReward: base.xp,
    telegraph: null,
    aiTimer: 0,
    bossPatternTimer: 0,
    phase: 1,
    isRaged: false,
    counterWindow: 0,
    freezeTimer: 0,
    freezeFxTimer: 0,
    slowedByDomain: false,
  };
}

module.exports = {
  ENEMY_TEMPLATES,
  createEnemy,
};
