"use strict";

const BASE_STATS = {
  "o-honrado": {
    maxHp: 307, maxEnergy: 560, energyRegen: 3, moveSpeed: 172,
    armor: 0, ccResist: 0.5, dodgeCooldown: 2.0, dodgeDistance: 125, radius: 38,
  },
  "portador-do-vinculo": {
    maxHp: 293, maxEnergy: 600, energyRegen: 3, moveSpeed: 178,
    armor: 0, ccResist: 0.5, dodgeCooldown: 2.0, dodgeDistance: 125, radius: 38,
  },
  "rei-amaldicoado": {
    maxHp: 367, maxEnergy: 480, energyRegen: 2, moveSpeed: 168,
    armor: 5, ccResist: 0.6, dodgeCooldown: 2.0, dodgeDistance: 130, radius: 40,
  },
  "punho-indomavel": {
    maxHp: 333, maxEnergy: 520, energyRegen: 3, moveSpeed: 180,
    armor: 3, ccResist: 0.4, dodgeCooldown: 2.0, dodgeDistance: 140, radius: 36,
  },
  "invocador-de-sombras": {
    maxHp: 283, maxEnergy: 640, energyRegen: 3, moveSpeed: 175,
    armor: 0, ccResist: 0.5, dodgeCooldown: 2.0, dodgeDistance: 125, radius: 36,
  },
  "lutador-de-sorte": {
    maxHp: 317, maxEnergy: 680, energyRegen: 4, moveSpeed: 170,
    armor: 0, ccResist: 0.3, dodgeCooldown: 2.0, dodgeDistance: 135, radius: 38,
  },
};

function resolveBaseStats(character) {
  return BASE_STATS[character] || BASE_STATS["o-honrado"];
}

function createPlayer({ id, sessionToken, name, x, y, now, character }) {
  const base = resolveBaseStats(character || "o-honrado");
  return {
    id,
    sessionToken,
    name,
    character: character || "o-honrado",
    kind: "player",
    x,
    y,
    vx: 0,
    vy: 0,
    aimX: x,
    aimY: y,
    radius: base.radius,
    alive: true,
    hp: base.maxHp,
    maxHp: base.maxHp,
    baseMaxHp: base.maxHp,
    armor: base.armor,
    energy: base.maxEnergy,
    maxEnergy: base.maxEnergy,
    baseMaxEnergy: base.maxEnergy,
    energyRegen: base.energyRegen,
    moveSpeed: base.moveSpeed,
    dodgeCooldownBase: base.dodgeCooldown,
    dodgeDistance: base.dodgeDistance,
    dodgeCooldown: 0,
    invulnTimer: 0,
    stunTimer: 0,
    stunFxTimer: 0,
    stunVisualTimer: 0,
    almaAbaladaTimer: 0,
    staringStacks: 0,
    staringAccumTimer: 0,
    staringDecayTimer: 0,
    hitFlash: 0,
    comboStep: 0,
    comboResetTimer: 0,
    m1Timer: 0,
    m1AnimTimer: 0,
    taidoBeatdownAnimState: null,
    animLockTimer: 0,
    domainRevealTimer: 0,
    dodgeTimer: 0,
    cast: null,
    flyingKnee: null,
    skillLock: false,
    domainExhaustionTimer: 0,
    domainCancelTimer: 0,
    cooldowns: {
      q: 0,
      e: 0,
      r: 0,
      space: 0,
      f: 0,
    },
    animState: "idle",
    statePriority: 8,
    input: {
      up: false,
      down: false,
      left: false,
      right: false,
      m1: false,
      q: false,
      e: false,
      r: false,
      space: false,
      f: false,
      dodge: false,
      aimX: x,
      aimY: y,
      seq: 0,
    },
    prevInput: {
      m1: false,
      q: false,
      e: false,
      r: false,
      space: false,
      f: false,
      dodge: false,
    },
    lastInputAt: now,
    lastAttackAt: now,
    lastDamageTaken: now,
    inputBurstCount: 0,
    inputBurstWindowStart: now,
    lastProcessedInputSeq: 0,
    kills: 0,
    deaths: 0,
    xp: 0,
    level: 1,
    xpToNext: 100,
    survivalXpTimer: 0,
    pendingUpgrades: null,
    pendingUpgradeExpiresAt: 0,
    appliedUpgrades: {},
    disconnectedAt: 0,
    offline: false,
    modifiers: {
      damageMul: 1,
      speedMul: 1,
      cooldownMul: 1,
      m1DamageMul: 1,
      energyRegenMul: 1,
      sustainOnKill: 0,
      blueRadiusMul: 1,
      bluePullMul: 1,
      blueDurationMul: 1,
      blueTickDamageMul: 1,
      redKnockbackMul: 1,
      redExplosionMul: 1,
      redDamageMul: 1,
      purpleWidthMul: 1,
      purpleLengthMul: 1,
      purpleDamageMul: 1,
      teleportCooldownMul: 1,
      teleportRecoveryMul: 1,
      teleportDistanceMul: 1,
      domainDrainMul: 1,
      domainRadiusMul: 1,
      domainSlowMul: 1,
      domainDurationMul: 1,
      domainPowerMul: 1,
      rikaDamageMul: 1,
      rikaCooldownMul: 1,
      dashSlashDamageMul: 1,
      dashSlashRangeMul: 1,
      fullRikaDurationMul: 1,
      fullRikaPowerMul: 1,
      pureLoveDamageMul: 1,
      pureLoveRadiusMul: 1,
      domainKatanaDamageMul: 1,
      damageReductionMul: 1,
    },
  };
}

module.exports = {
  BASE_STATS,
  createPlayer,
  resolveBaseStats,
};
